# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-terratest
  description: A GitHub action that runs terratest tests within the repo
  homepage: https://cloudposse.com/accelerate
  topics: ""

