name: "Terratest Test Runner"
description: "A GitHub Action to run Terratest tests and post the results as an artifact"
author: Cloud Posse <hello@cloudposse.com>
branding:
  icon: cloud-lightning
  color: blue
inputs:
  sourceDir:
    required: true
    description: The directory containing the source code to test
    default: "."
  testTimeout:
    required: false
    description: The timeout of the test
    default: "10m"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v3
      with:
        go-version-file: ${{ inputs.sourceDir }}/go.mod
        cache: true
        cache-dependency-path: ${{ inputs.sourceDir }}/go.mod

    - name: Run Tests
      shell: bash
      working-directory: ${{ inputs.sourceDir }}
      env:
        TTEST_TIMEOUT: ${{ inputs.testTimeout }}
      run: |
        go install github.com/jstemmer/go-junit-report@latest
        go test -timeout $TTEST_TIMEOUT -v ./... | go-junit-report -set-exit-code > report.xml

    - name: Post Test Summary
      uses: actions/upload-artifact@v3
      with:
        name: ttest-result
        path: ${{ inputs.sourceDir }}/report.xml
      if: always()
