name: Test Terratest GitHub Action
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The fully-formed ref of the branch or tag that triggered the workflow run"
        required: false
        type: "string"
      sha:
        description: "The sha of the commit that triggered the workflow run"
        required: false
        type: "string"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          sourceDir: "test/src"
